version: '3'
services:
  fastapi-app:
    image: python:3.12
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8010:8010"
    command: uvicorn main:app --host 0.0.0.0 --port 8010
